esphome:
  name: multi_coin_acceptor
  friendly_name: Multi Coin Acceptor

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "[your_api_encryption_key]"

ota:
  password: "[your_ota_password]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Multi Coin Acceptor"
    password: "fallback123"

captive_portal:

# Global variables
globals:
  - id: running
    type: bool
    restore_value: true
    initial_value: 'false'
  - id: in_bedrijf
    type: bool
    restore_value: true
    initial_value: 'false'
  - id: betaalde_seconden
    type: int
    restore_value: true
    initial_value: '0'

# Dimmable display brightness output
output:
  - platform: template
    id: display_brightness
    type: float
    write_action:
      - lambda: |-
          int level = int(state * 7.0);
          id(tm_display_1).set_intensity(level);
          id(tm_display_2).set_intensity(level);

light:
  - platform: output
    name: "Display Brightness"
    id: display_munt_helderheid
    output: display_brightness
    restore_mode: ALWAYS_ON

# Display 1
display:
  - platform: tm1637
    id: tm_display_1
    clk_pin: GPIO33
    dio_pin: GPIO25
    update_interval: 1s
    lambda: |-
      if (id(display_munt_helderheid).current_values.is_off()) return;
      int totaal = id(betaalde_seconden);
      int minuten = totaal / 60;
      int uren = minuten / 60;
      minuten = minuten % 60;
      bool knipper = (millis() / 1000) % 2 == 0;
      if (id(running) && knipper) {
        it.printf("%02d:%02d", uren, minuten);
      } else {
        it.printf("%02d %02d", uren, minuten);
      }

# Display 2
  - platform: tm1637
    id: tm_display_2
    clk_pin: GPIO35
    dio_pin: GPIO32
    update_interval: 1s
    lambda: |-
      if (id(display_munt_helderheid).current_values.is_off()) return;
      int totaal = id(betaalde_seconden);
      int minuten = totaal / 60;
      int uren = minuten / 60;
      minuten = minuten % 60;
      bool knipper = (millis() / 1000) % 2 == 0;
      if (id(running) && knipper) {
        it.printf("%02d:%02d", uren, minuten);
      } else {
        it.printf("%02d %02d", uren, minuten);
      }

# Adjustable parameters from Home Assistant
number:
  - platform: template
    name: "Heater Wattage"
    id: wattage
    unit_of_measurement: W
    min_value: 100.0
    max_value: 4000.0
    step: 100.0
    initial_value: 1800.0
    optimistic: true
  - platform: template
    name: "Price per kWh"
    id: prijs_per_kwh
    unit_of_measurement: €/kWh
    min_value: 0.01
    max_value: 1.0
    step: 0.01
    initial_value: 0.4
    optimistic: true

# Toggle for 'in_bedrijf' from Home Assistant
switch:
  - platform: template
    name: "In bedrijf"
    id: switch_in_bedrijf
    lambda: |-
      return id(in_bedrijf);
    turn_on_action:
      - lambda: 'id(in_bedrijf) = true;'
    turn_off_action:
      - lambda: |
          id(in_bedrijf) = false;
          id(running) = false;

# Start/Stop buttons
binary_sensor:
  - platform: gpio
    pin: GPIO23
    name: "Start/Stop Button 1"
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(in_bedrijf);'
            then:
              - lambda: 'id(running) = !id(running);'

  - platform: gpio
    pin: GPIO22
    name: "Start/Stop Button 2"
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(in_bedrijf);'
            then:
              - lambda: 'id(running) = !id(running);'

# Coin inputs
sensor:
  - platform: pulse_counter
    pin: GPIO18
    name: "Coin Slot 1"
    id: muntinvoer_1
    internal_filter: 13us
    update_interval: 200ms
    internal: true
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    filters:
      - lambda: |-
          if (x > 0) {
            int pulsen = int(x);
            float seconden_per_cent = (1000.0 * 3600.0) / (id(wattage).state * id(prijs_per_kwh).state);
            int toegevoegde_seconden = 0;
            switch (pulsen) {
              case 1: toegevoegde_seconden = int(seconden_per_cent * 10); break;
              case 2: toegevoegde_seconden = int(seconden_per_cent * 20); break;
              case 3: toegevoegde_seconden = int(seconden_per_cent * 50); break;
              case 4: toegevoegde_seconden = int(seconden_per_cent * 100); break;
              case 5: toegevoegde_seconden = int(seconden_per_cent * 200); break;
            }
            id(betaalde_seconden) += toegevoegde_seconden;
            id(in_bedrijf) = true;
          }
          return x;

  - platform: pulse_counter
    pin: GPIO19
    name: "Coin Slot 2"
    id: muntinvoer_2
    internal_filter: 13us
    update_interval: 200ms
    internal: true
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    filters:
      - lambda: |-
          if (x > 0) {
            int pulsen = int(x);
            float seconden_per_cent = (1000.0 * 3600.0) / (id(wattage).state * id(prijs_per_kwh).state);
            int toegevoegde_seconden = 0;
            switch (pulsen) {
              case 1: toegevoegde_seconden = int(seconden_per_cent * 10); break;
              case 2: toegevoegde_seconden = int(seconden_per_cent * 20); break;
              case 3: toegevoegde_seconden = int(seconden_per_cent * 50); break;
              case 4: toegevoegde_seconden = int(seconden_per_cent * 100); break;
              case 5: toegevoegde_seconden = int(seconden_per_cent * 200); break;
            }
            id(betaalde_seconden) += toegevoegde_seconden;
            id(in_bedrijf) = true;
          }
          return x;

# Solenoid output
switch:
  - platform: gpio
    name: "Coinbox Solenoid"
    pin: GPIO13
    id: solenoid

# Countdown logic
interval:
  - interval: 1s
    then:
      - if:
          condition:
            lambda: 'return id(running) && id(betaalde_seconden) > 0;'
          then:
            - lambda: 'id(betaalde_seconden)--;'
      - if:
          condition:
            lambda: 'return id(betaalde_seconden) == 0;'
          then:
            - lambda: |
                id(running) = false;
                id(in_bedrijf) = false;
